### ISSUE TITLE
Cannot use as a library

### ISSUE THREAD

**Issue by codeteo** [pavlospt/RoundedLetterView#1]
I'm trying to use it as a library but I get : 

Error:(9) No resource identifier found for attribute 'backgroundColorValue' in package 'teo.ram.css'
Error:(9) No resource identifier found for attribute 'titleColor' in package 'teo.ram.css'
Error:(9) No resource identifier found for attribute 'titleSize' in package 'teo.ram.css'
Error:(9) No resource identifier found for attribute 'titleText' in package 'teo.ram.css'

I have already added the dependency in my build.gradle file : 

```
compile 'com.github.pavlospt:roundedletterview:1.0'
```

At your Sample App code you just add the code as a java file : 

https://github.com/pavlospt/RoundedLetterView/blob/master/RoundedLetterView_SampleApp/app/src/main/java/gr/vanderbox/roundedletterview_sampleapp/view/RoundedLetterView.java

**Comment by vishal-chugh** [comment]
i cannot use this library 
same errors like above post are coming.

_My Dependency file:_
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.vishalchugh.krazysum"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:cardview-v7:23.3.0'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.github.pavlospt:roundedletterview:1.1'
}
`

**XML Code :** 
 ```
   <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:orientation="horizontal">

        <com.github.pavlospt.RoundedLetterView xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/rlv_name_view"
            android:layout_width="56dp"
            android:layout_height="56dp"
            app:backgroundColorValue="@color/green"
            app:titleColor="@android:color/white"
            app:titleSize="35dp"
            app:titleText="A" />

    </LinearLayout>
```

Error: 
C:\Users\Vishal Chugh\AndroidStudioProjects\myandroidprojects\KrazySum\app\src\main\res\layout\activity_play_field.xml
Error:(237) No resource identifier found for attribute 'backgroundColorValue' in package 'com.vishalchugh.krazysum'
Error:(237) No resource identifier found for attribute 'titleColor' in package 'com.vishalchugh.krazysum'
Error:(237) No resource identifier found for attribute 'titleSize' in package 'com.vishalchugh.krazysum'
Error:(237) No resource identifier found for attribute 'titleText' in package 'com.vishalchugh.krazysum'
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Android\sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

PLease HElp

**Comment by AlphaShawn** [comment]
You can use 
`compile 'com.github.pavlospt:roundedletterview:1.2'`
I find it can work in my project, and the attrs is slightly different from v1.1
