### ISSUE TITLE
Show tick mark

### ISSUE THREAD

**Issue by royale1223** [pavlospt/RoundedLetterView#4]
It would be nice if the library contains a method to swap the letter with a tick mark and grey/custom background like in the gmail app when an email is selected.

**Comment by pavlospt** [comment]
Yeah I know, but I decided not to implement this because there were already other libs filling that gap.

**Comment by royale1223** [comment]
Yes, but it's not single line easy.

One has to add a new library, wrap the view in a relativelayout, add a
sibling CircularImageView, swap visibility for these views in onBind.

I think, from your library it could be as simple as

letterView.showCheck(selected);
