### ISSUE TITLE
Error compiling RoundLetter Widget

### ISSUE THREAD

**Issue by larrytech7** [pavlospt/RoundedLetterView#5]
get this error when i try to compile my code with the library

Information:Gradle tasks [:app:assembleDebug]
----
----
Error:(11) No resource identifier found for attribute 'rlv_backgroundColorValue' in package 'com.iceteck.mobilemarts'
Error:(11) No resource identifier found for attribute 'rlv_titleColor' in package 'com.iceteck.mobilemarts'
Error:(11) No resource identifier found for attribute 'rlv_titleSize' in package 'com.iceteck.mobilemarts'
Error:(11) No resource identifier found for attribute 'rlv_titleText' in package 'com.iceteck.mobilemarts'
Error:Execution failed for task ':app:processDebugResources'.

I need help with this please.

**Comment by kvincent3** [comment]
The same error. Did you fix it ?

**Comment by pavlospt** [comment]
I can not reproduce it on my end. Can you provide some more info?

**Comment by kvincent3** [comment]
When I look into the library there is no files except a Manifest file in the META-INF folder. There is no class or XML files inside. Is that normal ?

**Comment by kvincent3** [comment]
![capture](https://cloud.githubusercontent.com/assets/13929927/14318941/75baa154-fc0f-11e5-9174-96bdaa40b755.png)

**Comment by pavlospt** [comment]
Weird. Can you fallback to 1.0 and let me check it and reupload it later?

**Comment by kvincent3** [comment]
It's exactly the same with the version 1.0. There is no other configuration to do before using it ? Or I have wrong configuration in my build.gradle file ? I can show you my  build.gradle file if that can help you to find thee issue.

![capture](https://cloud.githubusercontent.com/assets/13929927/14320634/1b3cb04e-fc16-11e5-8738-1a5a971cb4f7.png)

**Comment by pavlospt** [comment]
Version 1.2 is being uploaded as we speak. Resolves your issue :)
